apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-prod
  namespace: podinfo-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: podinfo.student-sepf.dski23a.timebertt.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo-prod
                port:
                  number: 80
  tls:
    - hosts:
        - podinfo.student-sepf.dski23a.timebertt.dev
      secretName: podinfo-prod-tls
