apiVersion: apps/v1
kind: Deployment
metadata:
  name: slides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slides
  template:
    metadata:
      labels:
        app: slides
    spec:
      containers:
        - name: server
          image: nginx:latest
          ports:
            - containerPort: 80

