
apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  type: LoadBalancer
  ports:
    # bestehender HTTP-Port bleibt wie im Original
    - name: http
      port: 9898
      targetPort: 9898
    # zusätzlicher Port 12000 für das Lab
    - name: http-lb
      port: 12000
      targetPort: 9898

