apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo-external-dns.yaml
  - external-dns/helmrelease.yaml
  - helmrepo-ingress-nginx.yaml
  - ingress-nginx/helmrelease.yaml
