apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/podinfo-dev.yaml
  - namespaces/podinfo-prod.yaml
  - infra/helmrepo-ingress-nginx.yaml
  - infra/ingress-nginx         # hat eigene kustomization.yaml
  - podinfo/dev
  - podinfo/prod
